name = "tabthedev/signally"
version = "0.1.4"
description = "A library which can generate class like RBXScriptSignal but custom event and more methods"
authors = ["tabthedev"]
repository = "https://github.com/tabthedev/Signally"
license = "MIT"
includes = [
  "pesde.toml",
  "README.md",
  "LICENSE",
  "src/**/*.luau",
]

[target]
environment = "roblox"
lib = "src/init.luau"

[indices]
default = "https://github.com/pesde-pkg/index"

[scripts]
build = "scripts/build.luau"

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.2.0", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.5.1", target = "lune" }

[engines]
pesde = "^0.7.0"
lune = "^0.10.2"
