name = "jiwonz/pathfs"
version = "0.6.0"
description = "luau-path + @lune/fs with some utilities"
license = "MIT"
authors = ["jiwonz <me@jiwonz.kr>", "jeparlefrancais <jeparlefrancais21@gmail.com>"]
repository = "https://github.com/jiwonz/lune-pathfs"
private = false
includes = ["README.md", "pesde.toml", "src/**", "LICENSE", "docs/**"]

[target]
environment = "lune"
lib = "src/lib.luau"

[engines]
pesde = "^0.7.1"
lune = "^0.10.2"

[dependencies.greentea]
name = "jiwonz/greentea_luau"
version = "^0.2.0"
index = "https://github.com/pesde-pkg/index"
target = "luau"

[dependencies.luau_path]
name = "jiwonz/luau_path"
version = "^0.2.0"
index = "https://github.com/pesde-pkg/index"
target = "luau"

[dev_dependencies.frktest]
name = "itsfrank/frktest"
version = "^0.0.4"
index = "https://github.com/pesde-pkg/index"
target = "luau"
