name = "jiwonz/luau_path"
version = "0.2.0"
description = "[Fork] A Luau library to handle file paths based on the Rust path library by jeparlefrancais, Uploaded for pesde"
license = "MIT"
authors = ["jiwonz <me@jiwonz.kr>", "jeparlefrancais <jeparlefrancais21@gmail.com>"]
repository = "https://github.com/jiwonz/luau-path"
private = false
includes = ["src/**", "README.md", "LICENSE.txt", "pesde.toml"]

[target]
environment = "luau"
lib = "src/init.luau"

[engines]
pesde = "^0.7.0"

[dependencies.luau_disk]
name = "jiwonz/luau_disk"
version = "^0.2.0"
index = "https://github.com/pesde-pkg/index"
